from __future__ import annotations

from reviewpilot.core.result import ReviewReport
from reviewpilot.core.severity import Severity

REPORT_MARKER = "<!-- reviewpilot:v1 -->"

_STATUS_LABEL = {
    "passed": "Passed",
    "failed": "Failed",
    "errored": "Errored",
    "skipped": "Skipped",
}

_SEVERITY_HEADING = {
    Severity.CRITICAL: "Critical Priority",
    Severity.HIGH: "High Priority",
    Severity.MEDIUM: "Medium Priority",
    Severity.LOW: "Low Priority",
}


def _format_counts(report: ReviewReport) -> str:
    counts = report.counts
    parts = []
    for sev in (Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW):
        n = counts[sev]
        if n > 0:
            parts.append(f"{n} {sev.value}")
    return ", ".join(parts) if parts else "0 issues"


def _format_finding(finding, index: int) -> str:
    lines = [f"#### {index}. {finding.title}", ""]
    if finding.page:
        lines.append(f"Page: `{finding.page}`  ")
    if finding.viewport:
        lines.append(f"Viewport: {finding.viewport}  ")
    if finding.page or finding.viewport:
        lines.append("")
    if finding.expected:
        lines.extend(["Expected:", finding.expected, ""])
    if finding.actual:
        lines.extend(["Actual:", finding.actual, ""])
    if finding.why_it_matters:
        lines.extend(["Why it matters:", finding.why_it_matters, ""])
    if finding.reproduction_steps:
        lines.append("Reproduction steps:")
        for step in finding.reproduction_steps:
            lines.append(f"1. {step}")
        lines.append("")
    if finding.evidence:
        lines.append("Evidence:")
        for ev in finding.evidence:
            lines.append(f"`{ev}`")
        lines.append("")
    if finding.suggested_fix:
        lines.extend(["Suggested fix:", finding.suggested_fix, ""])
    lines.append("---")
    return "\n".join(lines)


def generate_markdown_report(report: ReviewReport) -> str:
    status_label = _STATUS_LABEL.get(report.status.value, report.status.value)
    counts_line = _format_counts(report)
    journeys_reviewed = len([j for j in report.journeys if j.status.value != "skipped"])

    sections = [
        f"{REPORT_MARKER}",
        "## ReviewPilot Browser QA Report",
        "",
        f"Review target: {report.app_url}  ",
        f"Status: {status_label}  ",
        f"Journeys reviewed: {journeys_reviewed}  ",
        f"Issues found: {counts_line}",
        "",
    ]

    by_severity = report.findings_by_severity
    for sev in (Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW):
        findings = by_severity[sev]
        if not findings:
            continue
        sections.append(f"### {_SEVERITY_HEADING[sev]}")
        sections.append("")
        for i, finding in enumerate(findings, start=1):
            sections.append(_format_finding(finding, i))
        sections.append("")

    passed = report.passed_checks
    if passed:
        sections.append("### Passed Checks")
        sections.append("")
        for item in passed:
            sections.append(f"- {item}")
        sections.append("")

    errored = [j for j in report.journeys if j.status.value == "errored"]
    if errored:
        sections.append("### Errored Journeys")
        sections.append("")
        for j in errored:
            sections.append(f"- **{j.name}** ({j.viewport}): {', '.join(j.errors[:3]) or 'unknown error'}")
        sections.append("")

    sections.append("Generated by ReviewPilot, powered by Browser Use.")
    return "\n".join(sections)
